name: Build and Deploy

on:
  push:
    branches:
      - src

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: src
          token: ${{ secrets.TOKEN }}
      
      - name: Install
        run: npm ci

      - name: Build
        run: npm run build
      
      - name: Create local changes
        run: echo "mikeorozco.dev" >> dist/CNAME
      
      - name: Deploy
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: self
          BRANCH: main
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          FOLDER: dist
